comment&changes
CS-DictionaryTeam/switch pull request #79
Opened 2017-05-08 22:43 UTC by yparks

comments and delete userfragment

2017-05-09 00:57 UTC, RobertoAF commented on app/src/main/java/edu/mills/cs115/BaseFragment.java
> + *BaseFragment needs extends
Missing space between * and Base

2017-05-09 00:58 UTC, RobertoAF commented on app/src/main/java/edu/mills/cs115/BaseFragment.java
> +   *Created this class by Callback
Missing space

2017-05-09 00:58 UTC, RobertoAF commented on app/src/main/java/edu/mills/cs115/BaseFragment.java
> +   *Abstract class is declared, may not be instantiated, and require subclass to provide implementation
Missing space

2017-05-09 00:58 UTC, RobertoAF commented on app/src/main/java/edu/mills/cs115/BaseFragment.java
> +   *for the anstract methods.
Missing space

2017-05-09 00:58 UTC, RobertoAF commented on app/src/main/java/edu/mills/cs115/BaseFragment.java
> +   *Created Activity by Callack this method
Missing space

2017-05-09 00:58 UTC, RobertoAF commented on app/src/main/java/edu/mills/cs115/BaseFragment.java
> +   *When subclass needs connect with internt, rewrite this method to connect with internet
Missing space

2017-05-09 00:59 UTC, RobertoAF commented on app/src/main/java/edu/mills/cs115/DictionaryBean.java
> + *@author Ying Parks
Missing space

2017-05-09 01:01 UTC, RobertoAF requested changes

2017-05-09 01:01 UTC, RobertoAF commented on app/src/main/java/edu/mills/cs115/HomeFragment.java
> +    //Randome generate 4 memes pictures for banner
Random

2017-05-09 01:01 UTC, RobertoAF commented on app/src/main/java/edu/mills/cs115/HomeFragment.java
> +// Randome generate a word  as word of a day content
Random

2017-05-09 01:01 UTC, RobertoAF commented on app/src/main/java/edu/mills/cs115/HomeFragment.java
> +      //Randome generate a word form database
Random

2017-05-09 04:23 UTC, closed without merging

2017-05-15 20:01 UTC, espertus commented on app/src/main/java/edu/mills/cs115/HomeFragment.java
> +    //Randome generate 4 memes pictures for banner
Actually, "Randomly".